stages:
  - test
  - build

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_REG: $CI_REGISTRY_IMAGE
  DOCKER_TLS_CERTDIR: ''
  GOPROXY: https://goproxy.sl.supremind.info,https://goproxy.cn,https://gorpoxy.io,direct
  GOPRIVATE: git.supremind.info

before_script:
  - echo -e "machine git.supremind.info\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > /root/.netrc
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY || true

test csi:
  stage: test
  only:
    refs:
      - merge_requests
    changes:
      - platform/csi/**/*
  image: reg.supremind.info/hub/ci/golang-builder:latest
  script:
    - echo "done" # TODO: test need privilege

build csi:
  stage: build
  only:
    refs:
      - master
      - release
  image: reg.supremind.info/hub/ci/docker-runner:latest
  services:
    - name: docker:19.03-dind
      command:
      - --mtu=1450
      - --registry-mirror=https://docker.mirrors.ustc.edu.cn
  script:
    - export REGISTRY_NAME=${CI_REGISTRY_IMAGE}
    - make docker-push-ebsplugin
