apiVersion: v1
kind: Pod
metadata:
  name: test-ebs-csi
spec:
  restartPolicy: Never
  containers:
  - image: reg.supremind.info/hub/atom/test/debugger
    name: c
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: pv
      mountPath: /mnt/ebs
  volumes:
  - name: pv
    persistentVolumeClaim:
      claimName: ebs-pvc
