apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-ebs
provisioner: didiyun-ebs.csi.supremind.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  regionID: gz
  zoneID: gz02
  type: SSD
