kind: Service
apiVersion: v1
metadata:
  name: csi-dataset-controller
  labels:
    app: csi-dataset-controller
spec:
  selector:
    app: csi-dataset-controller
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-dataset-controller
spec:
  serviceName: "csi-dataset-controller"
  replicas: 1
  selector:
    matchLabels:
      app: csi-dataset-controller
  template:
    metadata:
      labels:
        app: csi-dataset-controller
    spec:
      serviceAccountName: csi-controller
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.0.1
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
          volumeMounts:
          - mountPath: /csi
            name: socket-dir

        - name: csi-provisioner
          image: reg.supremind.info/products/ava/ava/csi-provisioner:20190701-161d869cb
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: socket-dir

        - name: dataset
          image: datasetplugin:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          ports:
          - containerPort: 9898
            name: healthz
            protocol: TCP
          volumeMounts:
            - mountPath: /csi
              name: socket-dir

      volumes:
        - emptyDir: {}
          name: socket-dir
